django_docker_pycharm/djangodocker/urls.py
from django.conf.urls import url
from django.contrib import admin

from djangodocker import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^todos/add', views.add_todo),
    url(r'^todos/(?P<todo_id>\d+)/toggle', views.toggle_todo),
    url(r'^admin/', admin.site.urls),
]

django_docker_pycharm/djangodocker/models.py
from django.db import models


class Todo(models.Model):
    todo_text = models.CharField(max_length=400)
    created_at = models.DateTimeField(auto_now=True)
    done = models.BooleanField(default=False)

django_docker_pycharm/djangodocker/forms.py
from django import forms

class TaskForm(forms.Form):
    todo_text = forms.CharField(label='Add Task', label_suffix='', max_length=400)

django_docker_pycharm/djangodocker/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

from djangodocker.forms import TaskForm
from .models import Todo


def index(request):
    todos = Todo.objects.all()
    task_form = TaskForm()
    context = {
        'todos': todos,
        'task_form': task_form
    }
    return render(request, 'djangodocker/index.html', context)


def add_todo(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_todo = Todo()
            new_todo.todo_text = form.cleaned_data['todo_text']
            new_todo.save()

    return HttpResponseRedirect('/')


def toggle_todo(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.done = not todo.done
    todo.save()
    return JsonResponse({
        'id': todo.id,
        'done': todo.done
    })

django_docker_pycharm/djangodocker/templates/djangodocker/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todos</title>

    {% load static %}
    <script type="text/javascript" src="{% static "djangodocker/jquery-3.2.1.js" %}"></script>

    <script type="text/javascript">
        $(function() {

            // Django boilerplate for dealing with CSRF
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            var csrftoken = getCookie('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $(".todo input[type=checkbox]").on("click", function(e){
                var todo_checkbox = $(this);
                var id = todo_checkbox.data('id');

                $.post("/todos/" + id + "/toggle", {}, function(data){
                    // Toggle the checkbox
                    var checked = data.done;
                    todo_checkbox.prop('checked', checked);

                    // Set or remove parent div's "checked" class
                    var parent = todo_checkbox.parent();
                    if (checked){
                        parent.addClass('checked');
                    } else {
                        parent.removeClass('checked');
                    }
                })
            })
        });
    </script>

    <style>
        body {
            font-family: "Lato", sans-serif;
        }

        h1 {
            margin-left: 50px;
        }

        .task_form {
            margin-left: 50px;
            width: 800px;
            border: 5px solid black;
            padding-top: 30px;
            padding-bottom: 30px;
            padding-left: 15px;
            border-radius: 15px;
            margin-bottom: 35px;
        }

        .task_form label {
            font-size: 18px;
        }

        .task_form input {
            font-size: 18px;
        }

        #id_todo_text {
            width: 80%;
            margin-left: 10px;
        }

        .todo {
            margin-left:35px;
            height: 35px;
            margin-top: 15px;
            font-size: 18px;
        }

        .checked {
            text-decoration: line-through;
            color: #CCC;
        }

        .todo input[type=checkbox] {
            width: 40px;
        }
    </style>
</head>
<body>

<h1>Todo</h1>

<div class="task_form">
    <form action="/todos/add" method="post">
        {%  csrf_token %}
        {{ task_form }}
        <input type="submit" value="Add">
    </form>
</div>

{% for todo in todos %}
    <div class="todo{% if todo.done %} checked{% endif %}">
        <input
                type="checkbox"
                data-id="{{ todo.id }}"
                name="todo-{{ todo.id }}-checked"
                id="todo-{{ todo.id }}-checked"
                {% if todo.done %}
                    checked
                {% endif %}
                />
        <label for="todo-{{ todo.id }}-checked">
            {{ todo.todo_text }}
        </label>
    </div>
{% endfor %}

</body>
</html>